//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://alicebot.org/2001/AIML-1.0.1")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://alicebot.org/2001/AIML-1.0.1", IsNullable=false)]
public partial class aiml {
    
    private object[] itemsField;
    
    private aimlVersion versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("category", typeof(Category))]
    [System.Xml.Serialization.XmlElementAttribute("topic", typeof(aimlTopic))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public aimlVersion version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alicebot.org/2001/AIML-1.0.1")]
public partial class Category {
    
    private MixedPatternExpression patternField;
    
    private MixedPatternExpression thatField;
    
    private MixedTemplateContentContainer templateField;
    
    /// <remarks/>
    public MixedPatternExpression pattern {
        get {
            return this.patternField;
        }
        set {
            this.patternField = value;
        }
    }
    
    /// <remarks/>
    public MixedPatternExpression that {
        get {
            return this.thatField;
        }
        set {
            this.thatField = value;
        }
    }
    
    /// <remarks/>
    public MixedTemplateContentContainer template {
        get {
            return this.templateField;
        }
        set {
            this.templateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alicebot.org/2001/AIML-1.0.1")]
public partial class MixedPatternExpression {
    
    private BotPredicate[] itemsField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("bot")]
    public BotPredicate[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alicebot.org/2001/AIML-1.0.1")]
public partial class BotPredicate {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alicebot.org/2001/AIML-1.0.1")]
public partial class OneOrTwoDIndexedElement {
    
    private string indexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alicebot.org/2001/AIML-1.0.1")]
public partial class IndexedElement {
    
    private string indexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alicebot.org/2001/AIML-1.0.1")]
public partial class MixedTemplateContentContainer {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    [System.Xml.Serialization.XmlElementAttribute("bot", typeof(BotPredicate))]
    [System.Xml.Serialization.XmlElementAttribute("condition", typeof(MixedTemplateContentContainerCondition))]
    [System.Xml.Serialization.XmlElementAttribute("date", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("formal", typeof(MixedTemplateContentContainer))]
    [System.Xml.Serialization.XmlElementAttribute("gender", typeof(MixedTemplateContentContainer))]
    [System.Xml.Serialization.XmlElementAttribute("get", typeof(MixedTemplateContentContainerGet))]
    [System.Xml.Serialization.XmlElementAttribute("gossip", typeof(MixedTemplateContentContainer))]
    [System.Xml.Serialization.XmlElementAttribute("id", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("input", typeof(OneOrTwoDIndexedElement))]
    [System.Xml.Serialization.XmlElementAttribute("javascript", typeof(MixedTemplateContentContainer))]
    [System.Xml.Serialization.XmlElementAttribute("learn", typeof(string), DataType="anyURI")]
    [System.Xml.Serialization.XmlElementAttribute("lowercase", typeof(MixedTemplateContentContainer))]
    [System.Xml.Serialization.XmlElementAttribute("person", typeof(MixedTemplateContentContainer))]
    [System.Xml.Serialization.XmlElementAttribute("person2", typeof(MixedTemplateContentContainer))]
    [System.Xml.Serialization.XmlElementAttribute("random", typeof(MixedTemplateContentContainerRandom))]
    [System.Xml.Serialization.XmlElementAttribute("sentence", typeof(MixedTemplateContentContainer))]
    [System.Xml.Serialization.XmlElementAttribute("set", typeof(MixedTemplateContentContainerSet))]
    [System.Xml.Serialization.XmlElementAttribute("size", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("sr", typeof(object))]
    [System.Xml.Serialization.XmlElementAttribute("srai", typeof(MixedTemplateContentContainer))]
    [System.Xml.Serialization.XmlElementAttribute("star", typeof(IndexedElement))]
    [System.Xml.Serialization.XmlElementAttribute("system", typeof(MixedTemplateContentContainer))]
    [System.Xml.Serialization.XmlElementAttribute("that", typeof(OneOrTwoDIndexedElement))]
    [System.Xml.Serialization.XmlElementAttribute("thatstar", typeof(IndexedElement))]
    [System.Xml.Serialization.XmlElementAttribute("think", typeof(MixedTemplateContentContainer))]
    [System.Xml.Serialization.XmlElementAttribute("topicstar", typeof(IndexedElement))]
    [System.Xml.Serialization.XmlElementAttribute("uppercase", typeof(MixedTemplateContentContainer))]
    [System.Xml.Serialization.XmlElementAttribute("version", typeof(object))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://alicebot.org/2001/AIML-1.0.1")]
public partial class MixedTemplateContentContainerCondition {
    
    private System.Xml.XmlNode[] anyField;
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://alicebot.org/2001/AIML-1.0.1")]
public partial class MixedTemplateContentContainerGet {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://alicebot.org/2001/AIML-1.0.1")]
public partial class MixedTemplateContentContainerRandom {
    
    private MixedTemplateContentContainer[] liField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("li")]
    public MixedTemplateContentContainer[] li {
        get {
            return this.liField;
        }
        set {
            this.liField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://alicebot.org/2001/AIML-1.0.1")]
public partial class MixedTemplateContentContainerSet : MixedTemplateContentContainer {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://alicebot.org/2001/AIML-1.0.1", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("##any:")]
    Item,
    
    /// <remarks/>
    bot,
    
    /// <remarks/>
    condition,
    
    /// <remarks/>
    date,
    
    /// <remarks/>
    formal,
    
    /// <remarks/>
    gender,
    
    /// <remarks/>
    get,
    
    /// <remarks/>
    gossip,
    
    /// <remarks/>
    id,
    
    /// <remarks/>
    input,
    
    /// <remarks/>
    javascript,
    
    /// <remarks/>
    learn,
    
    /// <remarks/>
    lowercase,
    
    /// <remarks/>
    person,
    
    /// <remarks/>
    person2,
    
    /// <remarks/>
    random,
    
    /// <remarks/>
    sentence,
    
    /// <remarks/>
    set,
    
    /// <remarks/>
    size,
    
    /// <remarks/>
    sr,
    
    /// <remarks/>
    srai,
    
    /// <remarks/>
    star,
    
    /// <remarks/>
    system,
    
    /// <remarks/>
    that,
    
    /// <remarks/>
    thatstar,
    
    /// <remarks/>
    think,
    
    /// <remarks/>
    topicstar,
    
    /// <remarks/>
    uppercase,
    
    /// <remarks/>
    version,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://alicebot.org/2001/AIML-1.0.1")]
public partial class aimlTopic {
    
    private Category[] categoryField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("category")]
    public Category[] category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://alicebot.org/2001/AIML-1.0.1")]
public enum aimlVersion {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.0.1")]
    Item101,
}
