using ModernMUD;

namespace MUDEngine
{
    /// <summary>
    /// Map-based structures used in warfare.  Represents a building or fortification of some sort.
    /// </summary>
    public class WarfareStructure
    {
        public enum Type
        {
            Tower,
            Fort,
            Castle,
            Guardpost,
            /// <summary>
            /// A lookout post, typically a tree stand or high place with ladder-only access.
            /// </summary>
            Lookout,
            /// <summary>
            /// Can't be built by players, but autogenerated by zone placement.  Used for territory control.
            /// </summary>
            City
        }

        public WarfareStructure()
        {
            MaxOccupancy = 1;
            MaxHitPoints = 1;
            HitPoints = 1;
            InfluenceRadius = 1;
            UpkeepCost = 1;
            Location = null;
            SideOwnedBy = Race.RacewarSide.neutral;
            GuildOwnedBy = null;
            StructureType = Type.Lookout;
        }

        public Type StructureType { get; set; }

        public Guild GuildOwnedBy { get; set; }

        public Race.RacewarSide SideOwnedBy { get; set; }

        public Room Location { get; set; }

        public int UpkeepCost { get; set; }

        public int InfluenceRadius { get; set; }

        public int HitPoints { get; set; }

        public int MaxHitPoints { get; set; }

        public int MaxOccupancy { get; set; }
    }
}
