namespace ModernMUDEditor
{
    partial class SelectCommand
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.comboBox1 = new System.Windows.Forms.ComboBox();
            this.label1 = new System.Windows.Forms.Label();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnApply = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // comboBox1
            // 
            this.comboBox1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Items.AddRange(new object[] {
            "accuse",
            "ack",
            "afk",
            "aggressive",
            "agree",
            "amaze",
            "apologize",
            "applaud",
            "arch",
            "areas",
            "ask",
            "assist",
            "attributes",
            "auction",
            "awareness",
            "ayt",
            "backstab",
            "bandage",
            "bandaid",
            "bang",
            "banzai",
            "bark",
            "bash",
            "bath",
            "bbl",
            "beep",
            "beer",
            "beg",
            "berzerk",
            "bid",
            "bird",
            "bite",
            "bkiss",
            "blank",
            "bleed",
            "blindfold",
            "blink",
            "blow",
            "blush",
            "bodyslam",
            "boggle",
            "bonk",
            "boogie",
            "bored",
            "bot",
            "bottle",
            "bounce",
            "bounty",
            "bow",
            "brandish",
            "brb",
            "brief",
            "brush",
            "bug",
            "bungee",
            "burp",
            "buy",
            "bye",
            "cackle",
            "calm",
            "camp",
            "cant",
            "capture",
            "caress",
            "carve",
            "cast",
            "catnap",
            "chameleon",
            "channels",
            "charge",
            "cheek",
            "cheer",
            "cherish",
            "choke",
            "chuckle",
            "circle",
            "clans",
            "clap",
            "climb",
            "close",
            "clueless",
            "coffee",
            "color",
            "comb",
            "combine",
            "comfort",
            "commands",
            "compact",
            "compare",
            "congratulate",
            "consent",
            "consider",
            "cough",
            "cower",
            "crashbug",
            "credits",
            "cringe",
            "cry",
            "cuddle",
            "curious",
            "curse",
            "curtsey",
            "dance",
            "deposit",
            "description",
            "dice",
            "dirt",
            "disarm",
            "disband",
            "disembark",
            "disengage",
            "disgust",
            "dismount",
            "display",
            "dive",
            "dizzy",
            "doc",
            "doh",
            "doorbash",
            "down",
            "drag",
            "dream",
            "drink",
            "drool",
            "drop",
            "dropkick",
            "duck",
            "duh",
            "east",
            "eat",
            "economy",
            "embrace",
            "emote",
            "enter",
            "envy",
            "equipment",
            "eskimo",
            "examine",
            "exits",
            "experience",
            "eyebrow",
            "faction",
            "faint",
            "faith",
            "fart",
            "fidget",
            "fill",
            "firstaid",
            "flame",
            "flash",
            "flee",
            "flex",
            "flip",
            "flirt",
            "flower",
            "flutter",
            "fly",
            "follow",
            "fondle",
            "fool",
            "forage",
            "forget",
            "form",
            "fraglist",
            "french",
            "frown",
            "full",
            "fume",
            "fuzzy",
            "gag",
            "gape",
            "gasp",
            "gawk",
            "gcc",
            "german",
            "get",
            "ghug",
            "giggle",
            "give",
            "glance",
            "glare",
            "goose",
            "grab",
            "grimace",
            "grin",
            "groan",
            "grope",
            "group",
            "grovel",
            "growl",
            "grumble",
            "grunt",
            "gsay",
            "guard",
            "guilds",
            "gulp",
            "halo",
            "hand",
            "handcuff",
            "hangover",
            "happy",
            "headbutt",
            "heighten",
            "hello",
            "help",
            "hero",
            "hi5",
            "hiccup",
            "hickey",
            "hide",
            "hiss",
            "history",
            "hmm",
            "hold",
            "holdon",
            "hop",
            "hose",
            "howl",
            "hug",
            "hum",
            "hunger",
            "icecube",
            "idea",
            "ignore",
            "imitate",
            "impale",
            "innate",
            "innocent",
            "introduce",
            "inventory",
            "invite",
            "invoke",
            "jk",
            "jump",
            "justice",
            "kick",
            "kill",
            "kneel",
            "lag",
            "laugh",
            "layhands",
            "lean",
            "lick",
            "list",
            "lock",
            "look",
            "lost",
            "love",
            "lucky",
            "maim",
            "marvelous",
            "massage",
            "meditate",
            "melt",
            "memorize",
            "meow",
            "mmm",
            "mnm",
            "moan",
            "mooch",
            "moocow",
            "moon",
            "mosh",
            "mount",
            "mourn",
            "muhaha",
            "mutter",
            "nail",
            "nap",
            "nasty",
            "news",
            "ni",
            "nibble",
            "nod",
            "nog",
            "noogie",
            "north",
            "northeast",
            "northwest",
            "nose",
            "nudge",
            "nuke",
            "nuzzle",
            "ogle",
            "ohno",
            "oink",
            "ooo",
            "open",
            "order",
            "orders",
            "pace",
            "pagelength",
            "panic",
            "pant",
            "pat",
            "peck",
            "peer",
            "pet",
            "pick",
            "pillow",
            "pinch",
            "ping",
            "play",
            "plonk",
            "plot",
            "point",
            "poison",
            "poke",
            "ponder",
            "possum",
            "potato",
            "pounce",
            "poupon",
            "pour",
            "pout",
            "practice",
            "pray",
            "prompt",
            "propose",
            "protect",
            "pucker",
            "puke",
            "pull",
            "punch",
            "purr",
            "push",
            "put",
            "puzzle",
            "quaff",
            "quaff",
            "quit",
            "raise",
            "read",
            "ready",
            "reassure",
            "recite",
            "recline",
            "reload",
            "remove",
            "rent",
            "reply",
            "report",
            "requesthelp",
            "rescue",
            "rest",
            "roar",
            "rofl",
            "roll",
            "rose",
            "rub",
            "ruffle",
            "russian",
            "sad",
            "salute",
            "save",
            "say",
            "scan",
            "scare",
            "scold",
            "score",
            "scratch",
            "scream",
            "scribe",
            "search",
            "seduce",
            "sell",
            "senses",
            "shadow",
            "shake",
            "shift",
            "shiver",
            "shoot",
            "shout",
            "shove",
            "shrug",
            "shudder",
            "shush",
            "sigh",
            "sign",
            "sing",
            "sing",
            "sit",
            "skills",
            "skip",
            "slap",
            "sleep",
            "slobber",
            "smell",
            "smile",
            "smirk",
            "smoke",
            "smooch",
            "snap",
            "snarl",
            "sneak",
            "sneer",
            "sneeze",
            "snicker",
            "sniff",
            "snoogie",
            "snore",
            "snort",
            "snowball",
            "snuggle",
            "socials",
            "society",
            "songs",
            "south",
            "southeast",
            "southwest",
            "spam",
            "spanish",
            "spank",
            "speak",
            "spells",
            "spin",
            "spit",
            "split",
            "springleap",
            "squeal",
            "squeeze",
            "squirm",
            "squish",
            "stance",
            "stand",
            "stare",
            "steal",
            "steam",
            "stickup",
            "stomp",
            "strangle",
            "stretch",
            "strip",
            "strut",
            "suffer",
            "suicide",
            "sulk",
            "summon",
            "swat",
            "sweat",
            "sweep",
            "swoon",
            "tackle",
            "take",
            "tap",
            "tarzan",
            "taunt",
            "tease",
            "teeth",
            "tell",
            "tender",
            "thank",
            "think",
            "thirst",
            "throttle",
            "throw",
            "tickle",
            "time",
            "tip",
            "tiptoe",
            "toggle",
            "tongue",
            "torture",
            "toss",
            "touch",
            "track",
            "train",
            "trip",
            "trip",
            "trophy",
            "tug",
            "tummy",
            "tweak",
            "twibble",
            "twiddle",
            "twirl",
            "type",
            "typo",
            "unbind",
            "undress",
            "ungroup",
            "unlock",
            "untangle",
            "up",
            "use",
            "value",
            "veto",
            "visible",
            "wait",
            "wake",
            "wave",
            "weapon",
            "wear",
            "weather",
            "wedgie",
            "welcome",
            "west",
            "wet",
            "whap",
            "whatever",
            "wheeze",
            "whimper",
            "whine",
            "whirlwind",
            "whisper",
            "whistle",
            "who",
            "wield",
            "wiggle",
            "will",
            "wimpy",
            "wince",
            "wink",
            "wish",
            "withdraw",
            "wizlist",
            "worldmap",
            "worship",
            "wrap",
            "yawn",
            "yeehaw",
            "yell",
            "yodel",
            "zap",
            "zone",
            "zones"});
            this.comboBox1.Location = new System.Drawing.Point(72, 12);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new System.Drawing.Size(135, 21);
            this.comboBox1.TabIndex = 0;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(12, 15);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(54, 13);
            this.label1.TabIndex = 1;
            this.label1.Text = "Command";
            // 
            // btnCancel
            // 
            this.btnCancel.Location = new System.Drawing.Point(111, 50);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(75, 23);
            this.btnCancel.TabIndex = 5;
            this.btnCancel.Text = "Cancel";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnApply
            // 
            this.btnApply.Location = new System.Drawing.Point(30, 50);
            this.btnApply.Name = "btnApply";
            this.btnApply.Size = new System.Drawing.Size(75, 23);
            this.btnApply.TabIndex = 4;
            this.btnApply.Text = "OK";
            this.btnApply.UseVisualStyleBackColor = true;
            this.btnApply.Click += new System.EventHandler(this.btnApply_Click);
            // 
            // SelectCommand
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(219, 89);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnApply);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.comboBox1);
            this.Name = "SelectCommand";
            this.Text = "Select Command";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ComboBox comboBox1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnApply;
    }
}